#!/bin/bash

# Example scripts for running modular register comparison analysis
# Make sure you're in the Reduced2Canonical conda environment

echo "=================================================="
echo "MODULAR REGISTER COMPARISON ANALYSIS EXAMPLES"
echo "=================================================="

# Activate the conda environment (uncomment if needed)
# source /home/bhaashik/miniconda3/etc/profile.d/conda.sh
# conda activate Reduced2Canonical

echo ""
echo "1. BASIC ANALYSIS - Times-of-India only"
echo "   Fast analysis with feature counts and basic visualizations"
echo "   Command:"
echo "   python register_comparison/modular_analysis.py --newspapers 'Times-of-India' --analysis basic"
echo ""

echo "2. COMPREHENSIVE ANALYSIS - All newspapers"
echo "   Multi-dimensional analysis with statistical testing"
echo "   Command:"
echo "   python register_comparison/modular_analysis.py --newspapers all --analysis comprehensive"
echo ""

echo "3. FEATURE-VALUE ANALYSIS - Specific newspapers"
echo "   Complete transformation analysis with value-level details"
echo "   Command:"
echo "   python register_comparison/modular_analysis.py --newspapers 'Times-of-India,The-Hindu' --analysis feature-value"
echo ""

echo "4. ENHANCED VISUALIZATIONS - All newspapers with detailed value→value plots"
echo "   Complete analysis with enhanced transformation visualizations"
echo "   Command:"
echo "   python register_comparison/modular_analysis.py --newspapers all --analysis feature-value --enhance-visuals"
echo ""

echo "5. GLOBAL ANALYSIS ONLY - Cross-newspaper comparison"
echo "   Run only global analysis (requires previous newspaper analysis)"
echo "   Command:"
echo "   python register_comparison/modular_analysis.py --global-only --analysis feature-value"
echo ""

echo "=================================================="
echo "ANALYSIS OUTPUT LOCATIONS"
echo "=================================================="
echo "• Per-newspaper results: output/[Newspaper-Name]/"
echo "• Global analysis: output/GLOBAL_ANALYSIS/"
echo "• Enhanced visualizations: output/ENHANCED_TRANSFORMATIONS/"
echo "• Individual feature analysis: output/[Newspaper]/feature_analysis_[FEATURE].png"
echo ""

echo "=================================================="
echo "EXPECTED OUTPUTS"
echo "=================================================="
echo "Basic Analysis:"
echo "  • Feature frequency CSV files"
echo "  • Basic visualization plots"
echo "  • Statistical testing results"
echo ""
echo "Comprehensive Analysis:"
echo "  • Multi-dimensional breakdowns (by newspaper, parse type, cross-combinations)"
echo "  • 12+ comprehensive visualizations"
echo "  • LaTeX and Markdown reports"
echo ""
echo "Feature-Value Analysis:"
echo "  • Detailed transformation CSV files (22+ files)"
echo "  • Per-feature analysis files (18 features)"
echo "  • Value statistics and entropy analysis"
echo "  • Individual feature visualizations"
echo ""
echo "Enhanced Visualizations:"
echo "  • Transformation matrices (heatmaps)"
echo "  • Flow diagrams (Sankey-style)"
echo "  • Network graphs"
echo "  • Detailed breakdown plots"
echo ""

echo "=================================================="
echo "PERFORMANCE NOTES"
echo "=================================================="
echo "• Basic analysis: ~2-5 minutes per newspaper"
echo "• Comprehensive analysis: ~5-10 minutes per newspaper"
echo "• Feature-value analysis: ~10-15 minutes per newspaper"
echo "• Enhanced visualizations: +5-10 minutes additional"
echo "• Global analysis: Depends on number of newspapers analyzed"
echo ""

echo "=================================================="
echo "TO RUN A SPECIFIC EXAMPLE:"
echo "=================================================="
echo "1. Ensure you're in the project directory:"
echo "   cd /mnt/d/projects/Bhaashik/ReducedToCanonicalConvDiff"
echo ""
echo "2. Activate the conda environment:"
echo "   conda activate Reduced2Canonical"
echo ""
echo "3. Run one of the commands above, for example:"
echo "   python register_comparison/modular_analysis.py --newspapers 'Times-of-India' --analysis basic"
echo ""
echo "4. Check results in the output/ directory"
echo ""
echo "=================================================="